schema = 3

[mod]
[mod.'github.com/davecgh/go-spew']
version = 'v1.1.1'
hash = 'sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI='

[mod.'github.com/google/uuid']
version = 'v1.6.0'
hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

[mod.'github.com/klauspost/compress']
version = 'v1.18.4'
hash = 'sha256-swwNE6xKz4ZAOUHPWFlHYiqFeZLRZuuKYhLQ34aYnAU='

[mod.'github.com/kr/pretty']
version = 'v0.3.1'
hash = 'sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU='

[mod.'github.com/pierrec/lz4/v4']
version = 'v4.1.25'
hash = 'sha256-rpGrxdd36HU2aFtYjLET24v9qmqexkhCGwfPGGRoId0='

[mod.'github.com/pmezard/go-difflib']
version = 'v1.0.0'
hash = 'sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA='

[mod.'github.com/rogpeppe/go-internal']
version = 'v1.14.1'
hash = 'sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E='

[mod.'github.com/stretchr/testify']
version = 'v1.11.1'
hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

[mod.'github.com/twmb/franz-go']
version = 'v1.20.7'
hash = 'sha256-gt9x5AetuGTRrERsbrmAo+XtItLJx3ELAVYO5qhB0do='

[mod.'github.com/twmb/franz-go/pkg/kmsg']
version = 'v1.12.0'
hash = 'sha256-kVsUJI14rBBKxKYWMUbx6tZYpobdzSa/CbLDBAXa5rw='

[mod.'go.opentelemetry.io/otel']
version = 'v1.40.0'
hash = 'sha256-Cu9ZCLMAd9kGsmpnvoyqwm0IkF4Uk6Xo+8OsP9l+wUQ='

[mod.'go.opentelemetry.io/otel/sdk/metric']
version = 'v1.40.0'
hash = 'sha256-AxFp+vdl8yp6HRK+R73ClzxaCNtuHvL/zo4cBDwnMoU='

[mod.'golang.org/x/net']
version = 'v0.49.0'
hash = 'sha256-arK6PWwO9tQUJVb57QXUEXfgcB6ISI6qjVB0eC4zcnw='

[mod.'golang.org/x/sys']
version = 'v0.41.0'
hash = 'sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk='

[mod.'golang.org/x/text']
version = 'v0.34.0'
hash = 'sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM='

[mod.'google.golang.org/genproto/googleapis/rpc']
version = 'v0.0.0-20251202230838-ff82c1b0f217'
hash = 'sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA='

[mod.'google.golang.org/grpc']
version = 'v1.79.1'
hash = 'sha256-qJzroXZYo57MBIswxVVlXQuK/ubK1k9dAkD5btKCa4Y='

[mod.'google.golang.org/protobuf']
version = 'v1.36.11'
hash = 'sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE='

[mod.'gopkg.in/check.v1']
version = 'v1.0.0-20201130134442-10cb98267c6c'
hash = 'sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs='

[mod.'gopkg.in/yaml.v3']
version = 'v3.0.1'
hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
