// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package store

import (
	"context"
	"database/sql"
)

const insertClick = `-- name: InsertClick :exec
INSERT INTO fact_clicks (event_id, date_key, url_key, visitor_key, clicked_at_ms, referer_url)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertClickParams struct {
	EventID     []byte
	DateKey     int32
	UrlKey      int32
	VisitorKey  int32
	ClickedAtMs int64
	RefererUrl  sql.NullString
}

// Inserts a click fact record.
// caller is responsible for providing valid date_key and url_key values.
func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.ExecContext(ctx, insertClick,
		arg.EventID,
		arg.DateKey,
		arg.UrlKey,
		arg.VisitorKey,
		arg.ClickedAtMs,
		arg.RefererUrl,
	)
	return err
}

const insertVisitor = `-- name: InsertVisitor :exec
INSERT INTO dim_visitors (visitor_fp, ip_address, user_agent, browser_family, os_family)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE visitor_key = LAST_INSERT_ID(visitor_key)
`

type InsertVisitorParams struct {
	VisitorFp     []byte
	IpAddress     string
	UserAgent     sql.NullString
	BrowserFamily sql.NullString
	OsFamily      sql.NullString
}

// Inserts a new visitor or returns the existing visitor_key if visitor_fp already exists.
// Uses ON DUPLICATE KEY UPDATE to handle the unique constraint on visitor_fp.
// Note: caller should query for visitor_key using visitor_fp after this call.
func (q *Queries) InsertVisitor(ctx context.Context, arg InsertVisitorParams) error {
	_, err := q.db.ExecContext(ctx, insertVisitor,
		arg.VisitorFp,
		arg.IpAddress,
		arg.UserAgent,
		arg.BrowserFamily,
		arg.OsFamily,
	)
	return err
}
