// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: v1/analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrlRedirectedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// The short code that was accessed.
	ShortCode string `protobuf:"bytes,2,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	// Timestamp of when the click occurred, in milliseconds since epoch.
	ClickedAtMs int64 `protobuf:"varint,3,opt,name=clicked_at_ms,json=clickedAtMs,proto3" json:"clicked_at_ms,omitempty"`
	// IP address of the visitor.
	VisitorIp string `protobuf:"bytes,4,opt,name=visitor_ip,json=visitorIp,proto3" json:"visitor_ip,omitempty"`
	// User agent string of the visitor's browser or client.
	UserAgent string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// The referer URL, if available, indicating the source of the traffic.
	Referer       string `protobuf:"bytes,6,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlRedirectedEvent) Reset() {
	*x = UrlRedirectedEvent{}
	mi := &file_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlRedirectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlRedirectedEvent) ProtoMessage() {}

func (x *UrlRedirectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlRedirectedEvent.ProtoReflect.Descriptor instead.
func (*UrlRedirectedEvent) Descriptor() ([]byte, []int) {
	return file_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *UrlRedirectedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UrlRedirectedEvent) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *UrlRedirectedEvent) GetClickedAtMs() int64 {
	if x != nil {
		return x.ClickedAtMs
	}
	return 0
}

func (x *UrlRedirectedEvent) GetVisitorIp() string {
	if x != nil {
		return x.VisitorIp
	}
	return ""
}

func (x *UrlRedirectedEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UrlRedirectedEvent) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

var File_v1_analytics_proto protoreflect.FileDescriptor

const file_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x12v1/analytics.proto\x12\fanalytics.v1\"\xca\x01\n" +
	"\x12UrlRedirectedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\tshortCode\x12\"\n" +
	"\rclicked_at_ms\x18\x03 \x01(\x03R\vclickedAtMs\x12\x1d\n" +
	"\n" +
	"visitor_ip\x18\x04 \x01(\tR\tvisitorIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x06 \x01(\tR\arefererB.Z,github.com/Devin-Yeung/wormhole/analytics/pbb\x06proto3"

var (
	file_v1_analytics_proto_rawDescOnce sync.Once
	file_v1_analytics_proto_rawDescData []byte
)

func file_v1_analytics_proto_rawDescGZIP() []byte {
	file_v1_analytics_proto_rawDescOnce.Do(func() {
		file_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_analytics_proto_rawDesc), len(file_v1_analytics_proto_rawDesc)))
	})
	return file_v1_analytics_proto_rawDescData
}

var file_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_analytics_proto_goTypes = []any{
	(*UrlRedirectedEvent)(nil), // 0: analytics.v1.UrlRedirectedEvent
}
var file_v1_analytics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_analytics_proto_init() }
func file_v1_analytics_proto_init() {
	if File_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_analytics_proto_rawDesc), len(file_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_analytics_proto_goTypes,
		DependencyIndexes: file_v1_analytics_proto_depIdxs,
		MessageInfos:      file_v1_analytics_proto_msgTypes,
	}.Build()
	File_v1_analytics_proto = out.File
	file_v1_analytics_proto_goTypes = nil
	file_v1_analytics_proto_depIdxs = nil
}
