// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: v1/redirector.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedirectorService_Resolve_FullMethodName = "/redirector.v1.RedirectorService/Resolve"
)

// RedirectorServiceClient is the client API for RedirectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedirectorServiceClient interface {
	// Resolves a short code to its destination URL.
	//
	// Suggested status mapping:
	// - INVALID_ARGUMENT: short_code is malformed.
	// - NOT_FOUND: short code does not exist or is expired.
	// - UNAVAILABLE/DEADLINE_EXCEEDED/INTERNAL: backend/cache/storage failures.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type redirectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedirectorServiceClient(cc grpc.ClientConnInterface) RedirectorServiceClient {
	return &redirectorServiceClient{cc}
}

func (c *redirectorServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, RedirectorService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectorServiceServer is the server API for RedirectorService service.
// All implementations must embed UnimplementedRedirectorServiceServer
// for forward compatibility.
type RedirectorServiceServer interface {
	// Resolves a short code to its destination URL.
	//
	// Suggested status mapping:
	// - INVALID_ARGUMENT: short_code is malformed.
	// - NOT_FOUND: short code does not exist or is expired.
	// - UNAVAILABLE/DEADLINE_EXCEEDED/INTERNAL: backend/cache/storage failures.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	mustEmbedUnimplementedRedirectorServiceServer()
}

// UnimplementedRedirectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedirectorServiceServer struct{}

func (UnimplementedRedirectorServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedRedirectorServiceServer) mustEmbedUnimplementedRedirectorServiceServer() {}
func (UnimplementedRedirectorServiceServer) testEmbeddedByValue()                           {}

// UnsafeRedirectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedirectorServiceServer will
// result in compilation errors.
type UnsafeRedirectorServiceServer interface {
	mustEmbedUnimplementedRedirectorServiceServer()
}

func RegisterRedirectorServiceServer(s grpc.ServiceRegistrar, srv RedirectorServiceServer) {
	// If the following call panics, it indicates UnimplementedRedirectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedirectorService_ServiceDesc, srv)
}

func _RedirectorService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectorServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectorService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectorServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedirectorService_ServiceDesc is the grpc.ServiceDesc for RedirectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedirectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redirector.v1.RedirectorService",
	HandlerType: (*RedirectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _RedirectorService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/redirector.proto",
}
