// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: v1/redirector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The short code to resolve.
	// Expected format: 3-32 chars, [a-zA-Z0-9_-].
	ShortCode     *ShortCode `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_v1_redirector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_redirector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_v1_redirector_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetShortCode() *ShortCode {
	if x != nil {
		return x.ShortCode
	}
	return nil
}

type ResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL record containing the original URL and expiration info.
	UrlRecord     *UrlRecord `protobuf:"bytes,1,opt,name=url_record,json=urlRecord,proto3" json:"url_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_v1_redirector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_redirector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_v1_redirector_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetUrlRecord() *UrlRecord {
	if x != nil {
		return x.UrlRecord
	}
	return nil
}

var File_v1_redirector_proto protoreflect.FileDescriptor

const file_v1_redirector_proto_rawDesc = "" +
	"\n" +
	"\x13v1/redirector.proto\x12\rredirector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12v1/shortcode.proto\"H\n" +
	"\x0eResolveRequest\x126\n" +
	"\n" +
	"short_code\x18\x01 \x01(\v2\x17.shortcode.v1.ShortCodeR\tshortCode\"I\n" +
	"\x0fResolveResponse\x126\n" +
	"\n" +
	"url_record\x18\x01 \x01(\v2\x17.shortcode.v1.UrlRecordR\turlRecord2]\n" +
	"\x11RedirectorService\x12H\n" +
	"\aResolve\x12\x1d.redirector.v1.ResolveRequest\x1a\x1e.redirector.v1.ResolveResponseB.Z,github.com/Devin-Yeung/wormhole/analytics/pbb\x06proto3"

var (
	file_v1_redirector_proto_rawDescOnce sync.Once
	file_v1_redirector_proto_rawDescData []byte
)

func file_v1_redirector_proto_rawDescGZIP() []byte {
	file_v1_redirector_proto_rawDescOnce.Do(func() {
		file_v1_redirector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_redirector_proto_rawDesc), len(file_v1_redirector_proto_rawDesc)))
	})
	return file_v1_redirector_proto_rawDescData
}

var file_v1_redirector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_redirector_proto_goTypes = []any{
	(*ResolveRequest)(nil),  // 0: redirector.v1.ResolveRequest
	(*ResolveResponse)(nil), // 1: redirector.v1.ResolveResponse
	(*ShortCode)(nil),       // 2: shortcode.v1.ShortCode
	(*UrlRecord)(nil),       // 3: shortcode.v1.UrlRecord
}
var file_v1_redirector_proto_depIdxs = []int32{
	2, // 0: redirector.v1.ResolveRequest.short_code:type_name -> shortcode.v1.ShortCode
	3, // 1: redirector.v1.ResolveResponse.url_record:type_name -> shortcode.v1.UrlRecord
	0, // 2: redirector.v1.RedirectorService.Resolve:input_type -> redirector.v1.ResolveRequest
	1, // 3: redirector.v1.RedirectorService.Resolve:output_type -> redirector.v1.ResolveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_redirector_proto_init() }
func file_v1_redirector_proto_init() {
	if File_v1_redirector_proto != nil {
		return
	}
	file_v1_shortcode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_redirector_proto_rawDesc), len(file_v1_redirector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_redirector_proto_goTypes,
		DependencyIndexes: file_v1_redirector_proto_depIdxs,
		MessageInfos:      file_v1_redirector_proto_msgTypes,
	}.Build()
	File_v1_redirector_proto = out.File
	file_v1_redirector_proto_goTypes = nil
	file_v1_redirector_proto_depIdxs = nil
}
