// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: v1/shortcode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShortCodeKind indicates whether a short code was generated by the system or provided by the user.
type ShortCodeKind int32

const (
	// The short code was generated by the system.
	ShortCodeKind_Generated ShortCodeKind = 0
	// The short code was provided by the user (custom).
	ShortCodeKind_Custom ShortCodeKind = 1
)

// Enum value maps for ShortCodeKind.
var (
	ShortCodeKind_name = map[int32]string{
		0: "Generated",
		1: "Custom",
	}
	ShortCodeKind_value = map[string]int32{
		"Generated": 0,
		"Custom":    1,
	}
)

func (x ShortCodeKind) Enum() *ShortCodeKind {
	p := new(ShortCodeKind)
	*p = x
	return p
}

func (x ShortCodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShortCodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shortcode_proto_enumTypes[0].Descriptor()
}

func (ShortCodeKind) Type() protoreflect.EnumType {
	return &file_v1_shortcode_proto_enumTypes[0]
}

func (x ShortCodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShortCodeKind.Descriptor instead.
func (ShortCodeKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_shortcode_proto_rawDescGZIP(), []int{0}
}

// ShortCode defines a short code and its kind (generated or custom).
type ShortCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The short code string.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The kind of short code (generated or custom).
	Kind          ShortCodeKind `protobuf:"varint,2,opt,name=kind,proto3,enum=shortcode.v1.ShortCodeKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortCode) Reset() {
	*x = ShortCode{}
	mi := &file_v1_shortcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortCode) ProtoMessage() {}

func (x *ShortCode) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shortcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortCode.ProtoReflect.Descriptor instead.
func (*ShortCode) Descriptor() ([]byte, []int) {
	return file_v1_shortcode_proto_rawDescGZIP(), []int{0}
}

func (x *ShortCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortCode) GetKind() ShortCodeKind {
	if x != nil {
		return x.Kind
	}
	return ShortCodeKind_Generated
}

type UrlRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original URL associated with this short code.
	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// Expiration timestamp for this short code. If unset, it never expires.
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlRecord) Reset() {
	*x = UrlRecord{}
	mi := &file_v1_shortcode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlRecord) ProtoMessage() {}

func (x *UrlRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shortcode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlRecord.ProtoReflect.Descriptor instead.
func (*UrlRecord) Descriptor() ([]byte, []int) {
	return file_v1_shortcode_proto_rawDescGZIP(), []int{1}
}

func (x *UrlRecord) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UrlRecord) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

var File_v1_shortcode_proto protoreflect.FileDescriptor

const file_v1_shortcode_proto_rawDesc = "" +
	"\n" +
	"\x12v1/shortcode.proto\x12\fshortcode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\tShortCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.shortcode.v1.ShortCodeKindR\x04kind\"g\n" +
	"\tUrlRecord\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x127\n" +
	"\texpire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt**\n" +
	"\rShortCodeKind\x12\r\n" +
	"\tGenerated\x10\x00\x12\n" +
	"\n" +
	"\x06Custom\x10\x01B.Z,github.com/Devin-Yeung/wormhole/analytics/pbb\x06proto3"

var (
	file_v1_shortcode_proto_rawDescOnce sync.Once
	file_v1_shortcode_proto_rawDescData []byte
)

func file_v1_shortcode_proto_rawDescGZIP() []byte {
	file_v1_shortcode_proto_rawDescOnce.Do(func() {
		file_v1_shortcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shortcode_proto_rawDesc), len(file_v1_shortcode_proto_rawDesc)))
	})
	return file_v1_shortcode_proto_rawDescData
}

var file_v1_shortcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shortcode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shortcode_proto_goTypes = []any{
	(ShortCodeKind)(0),            // 0: shortcode.v1.ShortCodeKind
	(*ShortCode)(nil),             // 1: shortcode.v1.ShortCode
	(*UrlRecord)(nil),             // 2: shortcode.v1.UrlRecord
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_shortcode_proto_depIdxs = []int32{
	0, // 0: shortcode.v1.ShortCode.kind:type_name -> shortcode.v1.ShortCodeKind
	3, // 1: shortcode.v1.UrlRecord.expire_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shortcode_proto_init() }
func file_v1_shortcode_proto_init() {
	if File_v1_shortcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shortcode_proto_rawDesc), len(file_v1_shortcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shortcode_proto_goTypes,
		DependencyIndexes: file_v1_shortcode_proto_depIdxs,
		EnumInfos:         file_v1_shortcode_proto_enumTypes,
		MessageInfos:      file_v1_shortcode_proto_msgTypes,
	}.Build()
	File_v1_shortcode_proto = out.File
	file_v1_shortcode_proto_goTypes = nil
	file_v1_shortcode_proto_depIdxs = nil
}
