// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: v1/shortener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original URL to be shortened.
	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// Expiration time for the short URL, if not set, the short URL will never expire.
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// Optional custom alias for the short URL
	CustomAlias   *string `protobuf:"bytes,3,opt,name=custom_alias,json=customAlias,proto3,oneof" json:"custom_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_v1_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateRequest) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *CreateRequest) GetCustomAlias() string {
	if x != nil && x.CustomAlias != nil {
		return *x.CustomAlias
	}
	return ""
}

type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated short code for the original URL.
	ShortCode     *ShortCode `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_v1_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetShortCode() *ShortCode {
	if x != nil {
		return x.ShortCode
	}
	return nil
}

var File_v1_shortener_proto protoreflect.FileDescriptor

const file_v1_shortener_proto_rawDesc = "" +
	"\n" +
	"\x12v1/shortener.proto\x12\fshortener.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12v1/shortcode.proto\"\xa4\x01\n" +
	"\rCreateRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x127\n" +
	"\texpire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12&\n" +
	"\fcustom_alias\x18\x03 \x01(\tH\x00R\vcustomAlias\x88\x01\x01B\x0f\n" +
	"\r_custom_alias\"H\n" +
	"\x0eCreateResponse\x126\n" +
	"\n" +
	"short_code\x18\x01 \x01(\v2\x17.shortcode.v1.ShortCodeR\tshortCode2W\n" +
	"\x10ShortenerService\x12C\n" +
	"\x06Create\x12\x1b.shortener.v1.CreateRequest\x1a\x1c.shortener.v1.CreateResponseB.Z,github.com/Devin-Yeung/wormhole/analytics/pbb\x06proto3"

var (
	file_v1_shortener_proto_rawDescOnce sync.Once
	file_v1_shortener_proto_rawDescData []byte
)

func file_v1_shortener_proto_rawDescGZIP() []byte {
	file_v1_shortener_proto_rawDescOnce.Do(func() {
		file_v1_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shortener_proto_rawDesc), len(file_v1_shortener_proto_rawDesc)))
	})
	return file_v1_shortener_proto_rawDescData
}

var file_v1_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shortener_proto_goTypes = []any{
	(*CreateRequest)(nil),         // 0: shortener.v1.CreateRequest
	(*CreateResponse)(nil),        // 1: shortener.v1.CreateResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*ShortCode)(nil),             // 3: shortcode.v1.ShortCode
}
var file_v1_shortener_proto_depIdxs = []int32{
	2, // 0: shortener.v1.CreateRequest.expire_at:type_name -> google.protobuf.Timestamp
	3, // 1: shortener.v1.CreateResponse.short_code:type_name -> shortcode.v1.ShortCode
	0, // 2: shortener.v1.ShortenerService.Create:input_type -> shortener.v1.CreateRequest
	1, // 3: shortener.v1.ShortenerService.Create:output_type -> shortener.v1.CreateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shortener_proto_init() }
func file_v1_shortener_proto_init() {
	if File_v1_shortener_proto != nil {
		return
	}
	file_v1_shortcode_proto_init()
	file_v1_shortener_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shortener_proto_rawDesc), len(file_v1_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_shortener_proto_goTypes,
		DependencyIndexes: file_v1_shortener_proto_depIdxs,
		MessageInfos:      file_v1_shortener_proto_msgTypes,
	}.Build()
	File_v1_shortener_proto = out.File
	file_v1_shortener_proto_goTypes = nil
	file_v1_shortener_proto_depIdxs = nil
}
