// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysql

import (
	"database/sql"
)

// Visitor dimension: deduplicated profiles built from IP + User-Agent
type DimVisitor struct {
	VisitorKey int32
	// Fingerprint: SHA256 hash of IP + User-Agent
	VisitorFp []byte
	// Supports both IPv4 and IPv6
	IpAddress string
	// Raw User-Agent string
	UserAgent sql.NullString
	// Parsed browser family, e.g. Chrome / Firefox
	BrowserFamily sql.NullString
	// Parsed OS family, e.g. Windows / iOS
	OsFamily sql.NullString
}

// Fact: one row per click; UUIDv7 PK keeps inserts mostly ordered
type FactClick struct {
	// UUIDv7 stored as 16 bytes
	EventID []byte
	// FK -> dim_visitors
	VisitorKey int32
	// Unix epoch ms; source of truth
	ClickedAtMs int64
	ClickedAt   sql.NullTime
	// Raw HTTP Referer
	RefererUrl sql.NullString
}
