name: Build with Nix
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ matrix.os }}-check-${{ hashFiles('**/*.nix', 'Cargo.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ matrix.os }}-
          # collect garbage until Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 3221225472 # 3 Gib
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ matrix.os }}-check-
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never
      - name: Check Flake
        run: nix flake check
  build-binary:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
        pkg:
          - wormhole-redirector
          - wormhole-shortener
          - wormhole-gateway
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          # use flake checks' cache as source of truth
          save: false
          # restore and save a cache using this key
          primary-key: nix-${{ matrix.os }}-build-${{ hashFiles('**/*.nix', 'Cargo.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ matrix.os }}-
      - name: Build Package / ${{ matrix.os }} / ${{ matrix.pkg }}
        run: nix build .#${{ matrix.pkg }}
